/**
 * Curated, plain-language drug info for common medicines.
 * Keyed by lowercased salt/ingredient name (first active ingredient).
 *
 * This isn't medical advice — it's the kind of summary an Indian patient sees
 * on 1mg / Apollo product pages so they know what they're buying.
 */

export interface DrugDetail {
  uses: string;
  howItWorks: string;
  sideEffects: string;
  warnings: string;
  storage?: string;
  prescriptionRequired: boolean;
  soldOnline: boolean;
}

export const DRUG_DETAILS: Record<string, DrugDetail> = {

  // ── Pain & Fever ─────────────────────────────────────────────────────────
  paracetamol: {
    uses: "Relieves mild to moderate pain and reduces fever.",
    howItWorks: "Blocks chemical messengers in the brain that signal pain and raise body temperature.",
    sideEffects: "Generally well-tolerated. Rare: nausea, allergic rash, liver injury at high doses.",
    warnings: "Do not exceed 4g per day. Avoid with alcohol or pre-existing liver disease.",
    storage: "Store below 30°C, away from moisture and direct sunlight.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  ibuprofen: {
    uses: "Relieves pain, inflammation, and fever (headache, muscle ache, arthritis, period pain).",
    howItWorks: "Blocks prostaglandins, the chemicals that cause pain and swelling.",
    sideEffects: "Stomach upset, heartburn, dizziness. Long term: kidney or stomach bleeding.",
    warnings: "Take with food. Avoid in ulcers, kidney disease, pregnancy (3rd trimester).",
    prescriptionRequired: false,
    soldOnline: true,
  },
  aspirin: {
    uses: "Pain, fever, anti-clotting in cardiac patients.",
    howItWorks: "Inhibits cyclo-oxygenase, reducing prostaglandins and platelet aggregation.",
    sideEffects: "GI irritation, bleeding risk, tinnitus at high doses.",
    warnings: "Avoid in children with viral illness (Reye's syndrome). Consult before surgery.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  diclofenac: {
    uses: "Pain and inflammation in arthritis, injury, muscle pain, and post-operative pain.",
    howItWorks: "Non-steroidal anti-inflammatory drug that blocks COX enzymes to reduce prostaglandins.",
    sideEffects: "Stomach pain, nausea, headache, water retention. Rarely: GI bleed, kidney strain.",
    warnings: "Take with food. Avoid with other NSAIDs, in peptic ulcer, or kidney/heart failure.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  aceclofenac: {
    uses: "Rheumatoid arthritis, osteoarthritis, spondylitis, dental and post-operative pain.",
    howItWorks: "NSAID that selectively inhibits COX-2, reducing inflammation with less GI impact than older NSAIDs.",
    sideEffects: "Nausea, dyspepsia, abdominal pain, diarrhoea.",
    warnings: "Take with food. Avoid if you have peptic ulcer, kidney or heart failure.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  nimesulide: {
    uses: "Acute pain, fever, arthritis, dysmenorrhoea.",
    howItWorks: "Preferentially blocks COX-2 to reduce pain and inflammation.",
    sideEffects: "Nausea, dyspepsia, diarrhoea. Rare: liver toxicity.",
    warnings: "Not for children under 12 or patients with liver disease. Short-term use only.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  naproxen: {
    uses: "Arthritis, gout, menstrual cramps, muscle pain, headache.",
    howItWorks: "NSAID that inhibits COX-1 and COX-2, reducing prostaglandin synthesis.",
    sideEffects: "Stomach upset, heartburn, dizziness, fluid retention.",
    warnings: "Take with food. Long-term use increases cardiovascular and GI risk.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  tramadol: {
    uses: "Moderate to moderately severe pain (post-operative, cancer, injury).",
    howItWorks: "Binds opioid receptors and inhibits reuptake of serotonin/norepinephrine to reduce pain perception.",
    sideEffects: "Nausea, dizziness, constipation, headache, drowsiness.",
    warnings: "Habit-forming — use only as prescribed. Avoid alcohol. Do not drive.",
    prescriptionRequired: true,
    soldOnline: false,
  },
  tapentadol: {
    uses: "Moderate to severe acute pain.",
    howItWorks: "Opioid receptor agonist with norepinephrine reuptake inhibition for dual pain relief.",
    sideEffects: "Nausea, vomiting, dizziness, somnolence, constipation.",
    warnings: "Schedule H1 narcotic. Habit-forming. Do not combine with alcohol or sedatives.",
    prescriptionRequired: true,
    soldOnline: false,
  },
  morphine: {
    uses: "Severe pain in cancer, injury, or post-surgery.",
    howItWorks: "Strong opioid that binds mu-receptors in the brain to block pain signals.",
    sideEffects: "Drowsiness, constipation, nausea, respiratory depression at high doses.",
    warnings: "Controlled narcotic. Risk of dependence. Only for serious pain under strict supervision.",
    prescriptionRequired: true,
    soldOnline: false,
  },
  etoricoxib: {
    uses: "Osteoarthritis, rheumatoid arthritis, gout, ankylosing spondylitis.",
    howItWorks: "Selective COX-2 inhibitor reducing inflammation with lower GI risk than non-selective NSAIDs.",
    sideEffects: "Hypertension, oedema, headache, dyspepsia.",
    warnings: "Avoid in cardiovascular disease. Increases blood pressure — monitor regularly.",
    prescriptionRequired: true,
    soldOnline: true,
  },

  // ── Antibiotics & Anti-Infectives ─────────────────────────────────────────
  azithromycin: {
    uses: "Bacterial infections of the chest, throat, skin, and ear.",
    howItWorks: "Macrolide antibiotic that stops bacteria from making proteins needed to grow.",
    sideEffects: "Diarrhoea, nausea, abdominal pain, mild rash.",
    warnings: "Complete the full course. Avoid antacids within 2 hours. Tell doctor of heart conditions.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  amoxicillin: {
    uses: "Bacterial infections — chest, ear, throat, skin, urinary tract.",
    howItWorks: "Penicillin antibiotic that breaks down bacterial cell walls.",
    sideEffects: "Diarrhoea, rash, nausea. Seek help if rash spreads or breathing is difficult.",
    warnings: "Tell your doctor about any penicillin allergy.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  "amoxicillin clavulanate": {
    uses: "Respiratory, urinary tract, skin infections caused by bacteria resistant to plain amoxicillin.",
    howItWorks: "Amoxicillin kills bacteria; clavulanate blocks beta-lactamase enzymes that destroy it.",
    sideEffects: "Diarrhoea, nausea, vomiting, skin rash.",
    warnings: "Inform doctor of penicillin allergy. Liver enzyme elevations reported on long use.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  ciprofloxacin: {
    uses: "Urinary tract infections, typhoid, respiratory and GI tract infections.",
    howItWorks: "Fluoroquinolone antibiotic that blocks DNA gyrase, preventing bacterial replication.",
    sideEffects: "Nausea, diarrhoea, headache, dizziness. Rare: tendon rupture.",
    warnings: "Avoid antacids within 2 hours. Do not use in children under 18. Avoid sun exposure.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  levofloxacin: {
    uses: "Respiratory tract infections, urinary tract infections, sinusitis.",
    howItWorks: "Fluoroquinolone that inhibits bacterial topoisomerase IV and DNA gyrase.",
    sideEffects: "Nausea, diarrhoea, headache, insomnia.",
    warnings: "Risk of tendon rupture, especially in elderly and those on steroids.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  doxycycline: {
    uses: "Chest infections, STIs, malaria prevention, acne.",
    howItWorks: "Tetracycline antibiotic that blocks protein synthesis in bacteria.",
    sideEffects: "Photosensitivity, nausea, oesophageal irritation.",
    warnings: "Take with plenty of water. Don't lie down for 30 min after dose. Avoid in pregnancy.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  metronidazole: {
    uses: "Bacterial vaginosis, amoebic dysentery, giardiasis, anaerobic infections.",
    howItWorks: "Disrupts bacterial and protozoal DNA synthesis, killing the organisms.",
    sideEffects: "Metallic taste, nausea, headache, dark urine.",
    warnings: "Avoid alcohol completely during and for 48 hours after use.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  cefixime: {
    uses: "Ear, chest, and urinary tract infections.",
    howItWorks: "3rd generation cephalosporin that disrupts cell wall synthesis in bacteria.",
    sideEffects: "Diarrhoea, stomach upset, headache.",
    warnings: "Tell doctor if allergic to penicillin. Complete the full course.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  cefpodoxime: {
    uses: "Respiratory tract infections, UTIs, skin infections, otitis media.",
    howItWorks: "3rd generation oral cephalosporin that inhibits bacterial cell-wall synthesis.",
    sideEffects: "Diarrhoea, nausea, abdominal pain.",
    warnings: "Caution in penicillin-allergic patients. Complete full course.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  clindamycin: {
    uses: "Skin, soft tissue, bone infections and anaerobic infections.",
    howItWorks: "Lincosamide antibiotic that inhibits ribosomal protein synthesis in bacteria.",
    sideEffects: "Diarrhoea (rarely severe Clostridioides difficile colitis), nausea, rash.",
    warnings: "Seek medical help immediately if you get severe or bloody diarrhoea.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  linezolid: {
    uses: "MRSA and other resistant Gram-positive infections.",
    howItWorks: "Oxazolidinone antibiotic that blocks bacterial ribosomal assembly.",
    sideEffects: "Nausea, headache, low platelet count on long-term use.",
    warnings: "Avoid tyramine-rich foods. Monitor CBC on prolonged use.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  meropenem: {
    uses: "Severe hospital-acquired infections including sepsis, meningitis.",
    howItWorks: "Carbapenem beta-lactam that inhibits bacterial cell-wall synthesis.",
    sideEffects: "Nausea, diarrhoea, headache, injection site reactions.",
    warnings: "IV use only in hospital setting. Monitor renal function.",
    prescriptionRequired: true,
    soldOnline: false,
  },
  fluconazole: {
    uses: "Fungal infections: candidiasis (oral, vaginal, skin), cryptococcal meningitis.",
    howItWorks: "Triazole antifungal that blocks ergosterol synthesis in fungal cell membranes.",
    sideEffects: "Nausea, headache, abdominal pain, rash.",
    warnings: "Interacts with many drugs. Avoid in liver disease.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  itraconazole: {
    uses: "Fungal nail infections, ringworm, thrush, aspergillosis.",
    howItWorks: "Triazole antifungal that disrupts the fungal cell membrane.",
    sideEffects: "Nausea, stomach pain, headache, rash.",
    warnings: "Take with food. Many drug interactions. Avoid in heart failure.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  acyclovir: {
    uses: "Herpes simplex (cold sores, genital herpes), herpes zoster (shingles), chickenpox.",
    howItWorks: "Antiviral that blocks herpes virus DNA replication.",
    sideEffects: "Nausea, headache, dizziness. IV form: kidney toxicity.",
    warnings: "Drink plenty of fluids. Dose adjust in kidney disease.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  oseltamivir: {
    uses: "Treatment and prevention of influenza (flu).",
    howItWorks: "Neuraminidase inhibitor that prevents influenza virus from spreading between cells.",
    sideEffects: "Nausea, vomiting, headache.",
    warnings: "Start within 48 hours of symptom onset for best effect.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  chloroquine: {
    uses: "Malaria treatment and prevention; rheumatoid arthritis; lupus.",
    howItWorks: "Interferes with haem detoxification in malaria parasites; modulates immune response.",
    sideEffects: "Nausea, headache, visual disturbances on long-term use.",
    warnings: "Regular eye checks needed on long-term use. Check G6PD before use.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  hydroxychloroquine: {
    uses: "Rheumatoid arthritis, lupus, malaria prevention.",
    howItWorks: "Immunomodulator that reduces inflammation; anti-malarial mechanism similar to chloroquine.",
    sideEffects: "Nausea, skin rash, visual changes.",
    warnings: "Annual eye exam required on long-term use. Monitor cardiac conduction.",
    prescriptionRequired: true,
    soldOnline: true,
  },

  // ── Gastroenterology ─────────────────────────────────────────────────────
  pantoprazole: {
    uses: "Acidity, heartburn, GERD, stomach ulcers.",
    howItWorks: "Blocks the stomach's proton pumps, cutting acid production.",
    sideEffects: "Headache, diarrhoea, abdominal pain. Long term: low magnesium, B12, bone loss.",
    warnings: "Take 30-60 min before food. Don't use beyond 8 weeks without doctor advice.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  omeprazole: {
    uses: "GERD, peptic ulcers, H. pylori eradication (with antibiotics), Zollinger-Ellison syndrome.",
    howItWorks: "Proton pump inhibitor that irreversibly blocks H+/K+-ATPase in stomach lining.",
    sideEffects: "Headache, nausea, abdominal pain, diarrhoea.",
    warnings: "Long-term use linked to low magnesium and B12. Don't use >8 weeks OTC.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  rabeprazole: {
    uses: "GERD, peptic ulcer, acidity.",
    howItWorks: "Proton pump inhibitor with faster onset than older PPIs.",
    sideEffects: "Headache, diarrhoea, abdominal pain.",
    warnings: "Take before meals. Tell doctor if symptoms persist beyond 4 weeks.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  esomeprazole: {
    uses: "GERD, erosive esophagitis, peptic ulcer, acidity.",
    howItWorks: "S-isomer of omeprazole; more potent proton pump inhibitor.",
    sideEffects: "Headache, diarrhoea, nausea.",
    warnings: "Long-term use linked to hypomagnesaemia and C. diff infection.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  lansoprazole: {
    uses: "Peptic ulcer, GERD, H. pylori eradication.",
    howItWorks: "Proton pump inhibitor that reduces gastric acid secretion.",
    sideEffects: "Diarrhoea, headache, abdominal pain.",
    warnings: "Take 30 min before a meal. Avoid long-term use without medical supervision.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  ranitidine: {
    uses: "Acidity and ulcers (less commonly prescribed now).",
    howItWorks: "Blocks H2 histamine receptors in the stomach to reduce acid.",
    sideEffects: "Headache, constipation, diarrhoea.",
    warnings: "Many countries have suspended ranitidine due to NDMA contamination concerns.",
    prescriptionRequired: false,
    soldOnline: false,
  },
  famotidine: {
    uses: "Peptic ulcer, GERD, acidity.",
    howItWorks: "H2 blocker that reduces gastric acid production.",
    sideEffects: "Headache, dizziness, constipation.",
    warnings: "Use the lowest effective dose for the shortest time.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  domperidone: {
    uses: "Nausea, vomiting, bloating after meals.",
    howItWorks: "Speeds up stomach emptying by blocking dopamine in the gut.",
    sideEffects: "Headache, dry mouth, rare cardiac rhythm changes.",
    warnings: "Use shortest course possible. Tell doctor if you have heart issues.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  ondansetron: {
    uses: "Nausea and vomiting (chemotherapy, post-operative, pregnancy).",
    howItWorks: "Blocks 5-HT3 serotonin receptors in the gut and brain that trigger nausea.",
    sideEffects: "Headache, constipation, flushing.",
    warnings: "May prolong QT interval — caution in cardiac patients.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  metoclopramide: {
    uses: "Nausea, vomiting, gastroparesis, migraine-associated nausea.",
    howItWorks: "Dopamine antagonist that speeds gastric emptying and blocks vomiting centre.",
    sideEffects: "Drowsiness, restlessness, tardive dyskinesia on long-term use.",
    warnings: "Use for max 5 days. Not for children under 1 year.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  loperamide: {
    uses: "Acute and chronic diarrhoea, traveller's diarrhoea.",
    howItWorks: "Slows gut movement by binding opioid receptors in the intestine.",
    sideEffects: "Constipation, abdominal cramping, dizziness.",
    warnings: "Do not use in diarrhoea with fever or blood in stools.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  "oral rehydration salts": {
    uses: "Prevention and treatment of dehydration from diarrhoea and vomiting.",
    howItWorks: "Glucose-sodium co-transport replaces fluids and electrolytes lost in diarrhoea.",
    sideEffects: "Mild nausea if taken too fast. Generally very safe.",
    warnings: "Do not add extra water or salt. Seek IV fluids for severe dehydration.",
    prescriptionRequired: false,
    soldOnline: true,
  },

  // ── Cardiac & Hypertension ────────────────────────────────────────────────
  amlodipine: {
    uses: "High blood pressure, angina (chest pain).",
    howItWorks: "Relaxes blood vessels by blocking calcium channels in arterial walls.",
    sideEffects: "Ankle swelling, flushing, headache, dizziness.",
    warnings: "Take at the same time daily. Don't stop suddenly.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  atorvastatin: {
    uses: "High cholesterol, prevention of heart attack and stroke.",
    howItWorks: "Blocks HMG-CoA reductase, the enzyme the liver uses to make cholesterol.",
    sideEffects: "Muscle ache, mild liver enzyme rise, indigestion.",
    warnings: "Tell doctor if you get unexplained muscle pain or dark urine.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  rosuvastatin: {
    uses: "High LDL cholesterol, cardiovascular risk reduction.",
    howItWorks: "Potent statin that reduces hepatic cholesterol synthesis.",
    sideEffects: "Muscle pain, headache, abdominal pain.",
    warnings: "Avoid grapefruit juice. Monitor liver enzymes and CK levels.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  losartan: {
    uses: "Hypertension, heart failure, kidney protection in diabetes.",
    howItWorks: "Angiotensin II receptor blocker (ARB) that relaxes blood vessels.",
    sideEffects: "Dizziness, high potassium, kidney function changes.",
    warnings: "Do not use in pregnancy. Monitor kidney function and potassium.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  telmisartan: {
    uses: "Hypertension, cardiovascular risk reduction.",
    howItWorks: "ARB with long duration that blocks angiotensin II effects on blood vessels.",
    sideEffects: "Dizziness, upper respiratory infection, back pain.",
    warnings: "Avoid in pregnancy. Monitor potassium and renal function.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  ramipril: {
    uses: "Hypertension, heart failure, post-MI cardioprotection.",
    howItWorks: "ACE inhibitor that prevents angiotensin I conversion, lowering blood pressure.",
    sideEffects: "Persistent dry cough, dizziness, high potassium.",
    warnings: "Avoid in pregnancy. Switch to ARB if cough is intolerable.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  enalapril: {
    uses: "Hypertension, heart failure, asymptomatic left ventricular dysfunction.",
    howItWorks: "ACE inhibitor that reduces angiotensin II, causing vasodilation.",
    sideEffects: "Dry cough, dizziness, hyperkalemia.",
    warnings: "Monitor potassium and kidney function. Avoid in pregnancy.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  metoprolol: {
    uses: "Hypertension, angina, heart failure, arrhythmia, post-MI.",
    howItWorks: "Selective beta-1 blocker that slows heart rate and reduces cardiac workload.",
    sideEffects: "Fatigue, cold hands, dizziness, bradycardia.",
    warnings: "Do not stop abruptly — taper over 2 weeks. Caution in asthma.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  bisoprolol: {
    uses: "Heart failure, hypertension, angina.",
    howItWorks: "Highly selective beta-1 blocker reducing heart rate and oxygen demand.",
    sideEffects: "Fatigue, dizziness, cold extremities, sleep disturbance.",
    warnings: "Never stop abruptly. Safer in mild asthma than non-selective beta-blockers.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  nebivolol: {
    uses: "Hypertension, heart failure.",
    howItWorks: "Selective beta-1 blocker with vasodilatory effect via nitric oxide release.",
    sideEffects: "Headache, fatigue, dizziness, nausea.",
    warnings: "Taper gradually if stopping. Avoid in severe bradycardia or heart block.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  clopidogrel: {
    uses: "Prevention of blood clots after heart attack, stroke, or stent placement.",
    howItWorks: "Irreversibly inhibits platelet ADP receptors, preventing clot formation.",
    sideEffects: "Bleeding, bruising, stomach upset.",
    warnings: "Stop 5-7 days before surgery. Tell dentist before procedures.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  warfarin: {
    uses: "Prevention of blood clots (DVT, PE, atrial fibrillation, prosthetic heart valves).",
    howItWorks: "Blocks vitamin K-dependent clotting factors II, VII, IX, X.",
    sideEffects: "Bleeding (gums, cuts, internal), easy bruising.",
    warnings: "Requires frequent INR monitoring. Many food and drug interactions. Avoid alcohol.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  digoxin: {
    uses: "Heart failure, atrial fibrillation.",
    howItWorks: "Inhibits Na+/K+-ATPase, increasing calcium and strengthening heart contractions.",
    sideEffects: "Nausea, bradycardia, visual disturbances (yellow-green halos).",
    warnings: "Narrow therapeutic window — regular blood level monitoring required.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  furosemide: {
    uses: "Oedema (fluid retention) in heart failure, liver disease, kidney disease.",
    howItWorks: "Loop diuretic that blocks sodium-potassium-chloride cotransporter in kidneys.",
    sideEffects: "Frequent urination, low potassium, dizziness, muscle cramps.",
    warnings: "Monitor electrolytes regularly. Take in the morning to avoid night-time urination.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  spironolactone: {
    uses: "Heart failure, fluid retention, hyperaldosteronism, hormonal acne in women.",
    howItWorks: "Potassium-sparing diuretic that blocks aldosterone receptors.",
    sideEffects: "High potassium, breast tenderness, irregular periods.",
    warnings: "Avoid with ACE inhibitors/ARBs without monitoring potassium closely.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  nitroglycerin: {
    uses: "Acute angina (chest pain) relief.",
    howItWorks: "Converts to nitric oxide, relaxing coronary vessels and reducing cardiac workload.",
    sideEffects: "Headache, flushing, dizziness, low blood pressure.",
    warnings: "Sit down when using. Don't take with erectile dysfunction medicines.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  isosorbide: {
    uses: "Prevention of angina, heart failure.",
    howItWorks: "Nitrate that relaxes vascular smooth muscle via nitric oxide.",
    sideEffects: "Headache, dizziness, flushing.",
    warnings: "Tolerance can develop — a nitrate-free period each day is recommended.",
    prescriptionRequired: true,
    soldOnline: true,
  },

  // ── Diabetes ──────────────────────────────────────────────────────────────
  metformin: {
    uses: "Type 2 diabetes — controls blood sugar.",
    howItWorks: "Reduces glucose production by the liver and improves insulin sensitivity.",
    sideEffects: "Loose stools, metallic taste, vitamin B12 deficiency on long use.",
    warnings: "Take with meals. Stop temporarily before surgery or contrast scans.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  glimepiride: {
    uses: "Type 2 diabetes — stimulates insulin secretion.",
    howItWorks: "Sulfonylurea that binds potassium channels in pancreatic beta cells to release insulin.",
    sideEffects: "Hypoglycaemia, weight gain, nausea.",
    warnings: "Take with breakfast. Do not skip meals. Alcohol increases hypoglycaemia risk.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  gliclazide: {
    uses: "Type 2 diabetes.",
    howItWorks: "Sulfonylurea with lower hypoglycaemia risk than older agents due to shorter duration.",
    sideEffects: "Hypoglycaemia, nausea, weight gain.",
    warnings: "Ensure regular meals. Check blood sugar regularly.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  glipizide: {
    uses: "Type 2 diabetes.",
    howItWorks: "Short-acting sulfonylurea that stimulates pancreatic insulin release.",
    sideEffects: "Hypoglycaemia, nausea, headache.",
    warnings: "Take 30 min before meals. Monitor blood glucose.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  sitagliptin: {
    uses: "Type 2 diabetes — used alone or with metformin.",
    howItWorks: "DPP-4 inhibitor that increases incretin levels to stimulate insulin release.",
    sideEffects: "Runny nose, sore throat, headache. Rare: pancreatitis.",
    warnings: "Dose reduce in kidney disease. Stop if pancreatitis symptoms develop.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  vildagliptin: {
    uses: "Type 2 diabetes.",
    howItWorks: "DPP-4 inhibitor enhancing glucose-dependent insulin secretion.",
    sideEffects: "Dizziness, headache, rare liver enzyme elevation.",
    warnings: "Monitor liver function every 3 months in first year.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  dapagliflozin: {
    uses: "Type 2 diabetes, heart failure, chronic kidney disease.",
    howItWorks: "SGLT-2 inhibitor that causes the kidneys to excrete excess glucose in urine.",
    sideEffects: "Urinary tract and genital fungal infections, increased urination.",
    warnings: "Stop before surgery. Monitor for diabetic ketoacidosis (rare).",
    prescriptionRequired: true,
    soldOnline: true,
  },
  empagliflozin: {
    uses: "Type 2 diabetes with proven cardiovascular and kidney benefits.",
    howItWorks: "SGLT-2 inhibitor promoting urinary glucose excretion and reducing cardiac preload.",
    sideEffects: "Genital and urinary infections, increased urination, dizziness.",
    warnings: "Stop if unwell or fasting. Risk of Fournier's gangrene (rare).",
    prescriptionRequired: true,
    soldOnline: true,
  },
  pioglitazone: {
    uses: "Type 2 diabetes (often with metformin).",
    howItWorks: "Thiazolidinedione that activates PPAR-gamma to improve insulin sensitivity.",
    sideEffects: "Weight gain, fluid retention, increased fracture risk.",
    warnings: "Avoid in heart failure. Associated with bladder cancer risk on long-term use.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  insulin: {
    uses: "Type 1 diabetes; Type 2 diabetes when oral agents are insufficient.",
    howItWorks: "Replaces or supplements the body's own insulin to enable cellular glucose uptake.",
    sideEffects: "Hypoglycaemia, weight gain, injection site reactions.",
    warnings: "Always carry fast-acting sugar. Rotate injection sites. Store unopened vials in fridge.",
    storage: "Unopened: 2–8°C (fridge). In-use: room temperature up to 28 days.",
    prescriptionRequired: true,
    soldOnline: true,
  },

  // ── Respiratory ───────────────────────────────────────────────────────────
  montelukast: {
    uses: "Asthma prevention, allergic rhinitis.",
    howItWorks: "Blocks leukotriene receptors that cause bronchoconstriction and mucus secretion.",
    sideEffects: "Headache, abdominal pain, fatigue. Rare: mood changes.",
    warnings: "Take at night for asthma. Report neuropsychiatric symptoms to doctor.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  salbutamol: {
    uses: "Acute asthma attack (reliever inhaler), exercise-induced bronchospasm.",
    howItWorks: "Short-acting beta-2 agonist that quickly relaxes airway smooth muscle.",
    sideEffects: "Tremor, palpitations, headache, low potassium at high doses.",
    warnings: "Not for regular daily use — indicates poor asthma control. Use spacer in children.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  budesonide: {
    uses: "Asthma prevention, COPD, nasal polyps, allergic rhinitis.",
    howItWorks: "Corticosteroid that reduces airway inflammation and mucus production.",
    sideEffects: "Oral thrush, hoarseness (inhaler). Rinse mouth after use.",
    warnings: "Not for acute attacks. Do not stop abruptly in high doses.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  formoterol: {
    uses: "Asthma and COPD maintenance (always with a corticosteroid).",
    howItWorks: "Long-acting beta-2 agonist that keeps airways relaxed for 12 hours.",
    sideEffects: "Tremor, palpitations, headache.",
    warnings: "Never use as a rescue inhaler. Always combine with an ICS.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  salmeterol: {
    uses: "Asthma and COPD maintenance.",
    howItWorks: "Long-acting beta-2 agonist for sustained bronchodilation.",
    sideEffects: "Palpitations, tremor, headache.",
    warnings: "Use only with inhaled corticosteroid. Not for acute attacks.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  tiotropium: {
    uses: "COPD maintenance — reduces breathlessness and exacerbations.",
    howItWorks: "Long-acting anticholinergic that blocks muscarinic receptors causing bronchospasm.",
    sideEffects: "Dry mouth, constipation, urinary retention.",
    warnings: "Avoid in narrow-angle glaucoma or urinary retention. Do not swallow capsule.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  theophylline: {
    uses: "Asthma, COPD (second-line therapy).",
    howItWorks: "Bronchodilator and anti-inflammatory via phosphodiesterase inhibition.",
    sideEffects: "Nausea, headache, palpitations, insomnia. Toxicity risk at high levels.",
    warnings: "Narrow therapeutic window — requires blood level monitoring.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  "beclomethasone dipropionate": {
    uses: "Asthma prevention, allergic rhinitis.",
    howItWorks: "Inhaled corticosteroid reducing airway inflammation.",
    sideEffects: "Oral thrush, hoarseness, nasal dryness.",
    warnings: "Rinse mouth after inhaler use. Not a rescue medication.",
    prescriptionRequired: true,
    soldOnline: true,
  },

  // ── Allergy & ENT ─────────────────────────────────────────────────────────
  cetirizine: {
    uses: "Allergic rhinitis, urticaria (hives), itching.",
    howItWorks: "Non-sedating antihistamine that blocks H1 histamine receptors.",
    sideEffects: "Mild drowsiness, dry mouth, fatigue.",
    warnings: "Avoid alcohol. Use caution when driving.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  levocetirizine: {
    uses: "Allergic rhinitis, chronic urticaria, itching.",
    howItWorks: "Active R-enantiomer of cetirizine with higher potency at H1 receptors.",
    sideEffects: "Drowsiness, dry mouth, headache.",
    warnings: "Avoid alcohol and other sedating medicines.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  fexofenadine: {
    uses: "Seasonal allergic rhinitis, chronic urticaria.",
    howItWorks: "Non-sedating antihistamine with minimal CNS penetration.",
    sideEffects: "Headache, nausea, dizziness. Rarely drowsy.",
    warnings: "Avoid antacids containing aluminium/magnesium within 15 min.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  loratadine: {
    uses: "Allergic rhinitis, hives, skin itching.",
    howItWorks: "Long-acting non-sedating H1 antihistamine.",
    sideEffects: "Headache, dry mouth; minimal drowsiness.",
    warnings: "Safe in pregnancy (category B). Avoid in severe liver disease.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  desloratadine: {
    uses: "Allergic rhinitis, chronic urticaria.",
    howItWorks: "Active metabolite of loratadine; highly potent non-sedating antihistamine.",
    sideEffects: "Headache, dry mouth, fatigue.",
    warnings: "Generally safe and well tolerated.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  promethazine: {
    uses: "Nausea, vomiting, motion sickness, allergy.",
    howItWorks: "First-generation antihistamine that also blocks dopamine receptors.",
    sideEffects: "Drowsiness, dry mouth, blurred vision.",
    warnings: "Avoid driving. Not for children under 2 years.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  "xylometazoline": {
    uses: "Nasal congestion due to cold, sinusitis, or allergy.",
    howItWorks: "Alpha-adrenergic agonist that constricts nasal blood vessels.",
    sideEffects: "Nasal burning, rebound congestion on prolonged use.",
    warnings: "Do not use for more than 5-7 consecutive days.",
    prescriptionRequired: false,
    soldOnline: true,
  },

  // ── Neurology & Psychiatry ────────────────────────────────────────────────
  gabapentin: {
    uses: "Neuropathic pain, epilepsy (adjunctive), restless legs syndrome.",
    howItWorks: "Binds voltage-gated calcium channels in the CNS, reducing abnormal neuronal firing.",
    sideEffects: "Dizziness, drowsiness, weight gain, peripheral oedema.",
    warnings: "Do not stop abruptly. Dose reduce in renal impairment. Avoid alcohol.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  pregabalin: {
    uses: "Neuropathic pain, generalised anxiety disorder, epilepsy (adjunctive), fibromyalgia.",
    howItWorks: "Binds alpha-2-delta subunit of calcium channels, modulating neurotransmitter release.",
    sideEffects: "Dizziness, drowsiness, weight gain, oedema.",
    warnings: "Habit-forming potential. Taper slowly when stopping. Avoid driving.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  carbamazepine: {
    uses: "Epilepsy, trigeminal neuralgia, bipolar disorder.",
    howItWorks: "Stabilises voltage-gated sodium channels, reducing neuronal firing.",
    sideEffects: "Drowsiness, diplopia, nausea. Rarely: aplastic anaemia, Stevens-Johnson syndrome.",
    warnings: "Regular CBC and liver function monitoring. Many drug interactions.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  valproate: {
    uses: "Epilepsy, bipolar disorder, migraine prevention.",
    howItWorks: "Increases GABA levels and blocks sodium channels to stabilise neuronal activity.",
    sideEffects: "Weight gain, tremor, hair loss, liver toxicity.",
    warnings: "Highly teratogenic — avoid in women of childbearing age without contraception. Monitor LFTs.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  phenytoin: {
    uses: "Epilepsy, status epilepticus.",
    howItWorks: "Blocks voltage-gated sodium channels to prevent neuronal hyperexcitability.",
    sideEffects: "Gingival hyperplasia, nystagmus, ataxia, hirsutism.",
    warnings: "Narrow therapeutic window — blood level monitoring essential. Interacts with many drugs.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  levetiracetam: {
    uses: "Epilepsy (focal and generalised seizures, adjunctive).",
    howItWorks: "Binds synaptic vesicle protein SV2A, modulating neurotransmitter release.",
    sideEffects: "Irritability, aggression, drowsiness, headache.",
    warnings: "Monitor for mood and behavioural changes. Dose reduce in renal impairment.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  sertraline: {
    uses: "Depression, OCD, panic disorder, PTSD, social anxiety.",
    howItWorks: "Selective serotonin reuptake inhibitor (SSRI) increasing serotonin in brain synapses.",
    sideEffects: "Nausea, diarrhoea, insomnia, sexual dysfunction.",
    warnings: "Full effect takes 4-8 weeks. Do not stop abruptly. Monitor for suicidality initially.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  fluoxetine: {
    uses: "Depression, OCD, bulimia nervosa, panic disorder.",
    howItWorks: "SSRI with long half-life — fewer withdrawal symptoms than other SSRIs.",
    sideEffects: "Nausea, insomnia, anxiety (initially), sexual dysfunction.",
    warnings: "Long half-life means drug interactions persist after stopping.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  escitalopram: {
    uses: "Depression, generalised anxiety disorder.",
    howItWorks: "Most selective SSRI with good tolerability.",
    sideEffects: "Nausea, insomnia, sweating, sexual dysfunction.",
    warnings: "Avoid abrupt withdrawal. Monitor for QTc prolongation at high doses.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  venlafaxine: {
    uses: "Depression, generalised anxiety disorder, social phobia, panic disorder.",
    howItWorks: "SNRI that inhibits serotonin and norepinephrine reuptake.",
    sideEffects: "Nausea, dizziness, sweating, increased blood pressure at high doses.",
    warnings: "Do not stop abruptly — taper slowly. Monitor BP. Avoid in uncontrolled hypertension.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  amitriptyline: {
    uses: "Depression, neuropathic pain, migraine prevention, fibromyalgia.",
    howItWorks: "Tricyclic antidepressant blocking reuptake of serotonin and norepinephrine.",
    sideEffects: "Dry mouth, sedation, constipation, urinary retention, cardiac arrhythmia.",
    warnings: "Cardiotoxic in overdose. Avoid in heart disease. Anticholinergic effects.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  olanzapine: {
    uses: "Schizophrenia, bipolar disorder (acute mania).",
    howItWorks: "Atypical antipsychotic blocking dopamine D2 and serotonin 5HT2A receptors.",
    sideEffects: "Significant weight gain, sedation, metabolic syndrome, diabetes.",
    warnings: "Regular weight, blood glucose, and lipid monitoring. Risk of tardive dyskinesia.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  risperidone: {
    uses: "Schizophrenia, bipolar disorder, irritability in autism.",
    howItWorks: "Atypical antipsychotic with D2/5HT2A blockade and lower metabolic side effects.",
    sideEffects: "Weight gain, extrapyramidal symptoms, hyperprolactinaemia.",
    warnings: "Monitor metabolic parameters. Elevated prolactin can cause sexual side effects.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  clonazepam: {
    uses: "Epilepsy, panic disorder, anxiety, akathisia.",
    howItWorks: "Long-acting benzodiazepine that enhances GABA-A receptor activity.",
    sideEffects: "Sedation, dependence, cognitive impairment.",
    warnings: "Habit-forming. Do not stop suddenly. Avoid alcohol.",
    prescriptionRequired: true,
    soldOnline: false,
  },
  alprazolam: {
    uses: "Panic disorder, anxiety (short-term use only).",
    howItWorks: "Short-acting benzodiazepine that potentiates GABAergic inhibition.",
    sideEffects: "Sedation, dependence, memory impairment, rebound anxiety.",
    warnings: "High dependence potential. For acute use only. Taper slowly.",
    prescriptionRequired: true,
    soldOnline: false,
  },
  diazepam: {
    uses: "Anxiety, muscle spasm, alcohol withdrawal, status epilepticus.",
    howItWorks: "Long-acting benzodiazepine that enhances GABA inhibitory neurotransmission.",
    sideEffects: "Sedation, dependence, impaired coordination, paradoxical agitation.",
    warnings: "High dependence potential. Avoid in pregnancy and the elderly.",
    prescriptionRequired: true,
    soldOnline: false,
  },
  zolpidem: {
    uses: "Short-term insomnia.",
    howItWorks: "Non-benzodiazepine hypnotic that binds GABA-A receptors to promote sleep.",
    sideEffects: "Next-morning drowsiness, headache, parasomnias (sleep-walking).",
    warnings: "Use for max 4 weeks. Risk of dependence. Avoid alcohol.",
    prescriptionRequired: true,
    soldOnline: false,
  },
  donepezil: {
    uses: "Alzheimer's disease dementia.",
    howItWorks: "Reversible acetylcholinesterase inhibitor increasing acetylcholine in the brain.",
    sideEffects: "Nausea, diarrhoea, insomnia, muscle cramps.",
    warnings: "Take at bedtime to reduce nausea. Tell doctor of cardiac conduction abnormalities.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  sumatriptan: {
    uses: "Acute migraine with or without aura.",
    howItWorks: "Selective 5-HT1B/1D agonist that constricts dilated cranial blood vessels.",
    sideEffects: "Chest tightness, flushing, tingling, dizziness.",
    warnings: "Not for hemiplegic migraine. Avoid in cardiovascular disease.",
    prescriptionRequired: true,
    soldOnline: true,
  },

  // ── Thyroid ───────────────────────────────────────────────────────────────
  levothyroxine: {
    uses: "Hypothyroidism (underactive thyroid), goitre, thyroid cancer.",
    howItWorks: "Synthetic T4 hormone that replaces deficient thyroid hormone.",
    sideEffects: "Palpitations, weight loss, sweating, insomnia if dose too high.",
    warnings: "Take on empty stomach 30-60 min before breakfast. Many drug interactions.",
    storage: "Store below 30°C, away from humidity and light.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  methimazole: {
    uses: "Hyperthyroidism (overactive thyroid, Graves' disease).",
    howItWorks: "Blocks thyroid peroxidase, reducing thyroid hormone synthesis.",
    sideEffects: "Skin rash, joint pain. Rare: agranulocytosis (low white cells).",
    warnings: "Report fever or sore throat immediately (possible agranulocytosis).",
    prescriptionRequired: true,
    soldOnline: true,
  },
  carbimazole: {
    uses: "Hyperthyroidism.",
    howItWorks: "Prodrug of methimazole that inhibits thyroid hormone synthesis.",
    sideEffects: "Rash, nausea, joint pain, rare agranulocytosis.",
    warnings: "Report sore throat or fever immediately. Regular white cell count needed.",
    prescriptionRequired: true,
    soldOnline: true,
  },

  // ── Vitamins & Supplements ────────────────────────────────────────────────
  "vitamin d3": {
    uses: "Vitamin D deficiency, bone health, calcium absorption.",
    howItWorks: "Fat-soluble vitamin essential for calcium and phosphate metabolism and bone mineralisation.",
    sideEffects: "Hypercalcaemia at very high doses: nausea, weakness, kidney stones.",
    warnings: "High-dose supplementation (>4000 IU/day) needs doctor supervision.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  "cholecalciferol": {
    uses: "Vitamin D deficiency, rickets, osteoporosis prevention.",
    howItWorks: "Vitamin D3 form that is converted in liver and kidney to active calcitriol.",
    sideEffects: "Hypercalcaemia in excess. Generally very safe at recommended doses.",
    warnings: "Avoid doses >4000 IU/day long-term without monitoring serum calcium.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  "calcium carbonate": {
    uses: "Calcium supplementation, osteoporosis, hyperphosphataemia in kidney disease.",
    howItWorks: "Provides elemental calcium for bone mineralisation and muscle function.",
    sideEffects: "Constipation, bloating, gas.",
    warnings: "Take with food. Avoid excessive doses (>2500 mg calcium/day).",
    prescriptionRequired: false,
    soldOnline: true,
  },
  "ferrous sulphate": {
    uses: "Iron-deficiency anaemia.",
    howItWorks: "Provides iron for haemoglobin and myoglobin synthesis.",
    sideEffects: "Constipation, dark stools, nausea, stomach upset.",
    warnings: "Take on empty stomach with vitamin C. Keep away from children (overdose risk).",
    prescriptionRequired: false,
    soldOnline: true,
  },
  "folic acid": {
    uses: "Folate deficiency anaemia, neural tube defect prevention in pregnancy.",
    howItWorks: "Essential co-factor for DNA synthesis and cell division.",
    sideEffects: "Generally very safe. Rare: allergic reactions.",
    warnings: "Start 3 months before conception for neural tube defect prevention.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  "cyanocobalamin": {
    uses: "Vitamin B12 deficiency, pernicious anaemia, peripheral neuropathy.",
    howItWorks: "Synthetic B12 essential for nerve myelin and red blood cell formation.",
    sideEffects: "Generally very safe. Rare: injection site pain, allergic reaction.",
    warnings: "Strict vegetarians/vegans at risk — supplement regularly.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  "methylcobalamin": {
    uses: "Vitamin B12 deficiency, neuropathy, megaloblastic anaemia.",
    howItWorks: "Active co-enzyme form of B12 directly used by nerve cells and for DNA synthesis.",
    sideEffects: "Well-tolerated. Rare: nausea, headache.",
    warnings: "Preferred form for neuropathy. Store away from light.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  zinc: {
    uses: "Zinc deficiency, diarrhoea (children), wound healing, immune support.",
    howItWorks: "Essential trace mineral for enzyme function, immune response, and cell division.",
    sideEffects: "Nausea, vomiting, metallic taste. Long-term high doses cause copper deficiency.",
    warnings: "Do not exceed 40 mg elemental zinc/day without medical supervision.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  magnesium: {
    uses: "Magnesium deficiency, muscle cramps, constipation (oxide form).",
    howItWorks: "Essential mineral for over 300 enzyme reactions, muscle contraction, and nerve function.",
    sideEffects: "Diarrhoea (high doses), nausea.",
    warnings: "Reduce dose if diarrhoea occurs. Caution in kidney disease.",
    prescriptionRequired: false,
    soldOnline: true,
  },

  // ── Dermatology ───────────────────────────────────────────────────────────
  betamethasone: {
    uses: "Inflammatory and allergic skin conditions (eczema, psoriasis, dermatitis).",
    howItWorks: "Potent corticosteroid that suppresses inflammatory mediators in the skin.",
    sideEffects: "Skin thinning, stretch marks, increased hair growth at application site.",
    warnings: "Do not use on face or skin folds for prolonged periods. Avoid in fungal infections.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  clobetasol: {
    uses: "Severe psoriasis, recalcitrant eczema.",
    howItWorks: "Super-potent topical corticosteroid with strong anti-inflammatory action.",
    sideEffects: "Skin atrophy, striae, telangiectasia.",
    warnings: "Use for maximum 4 weeks. Do not use on face or in children.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  hydrocortisone: {
    uses: "Mild inflammatory skin conditions, insect bites, nappy rash.",
    howItWorks: "Mild topical corticosteroid reducing skin inflammation and itching.",
    sideEffects: "Mild skin thinning on prolonged use.",
    warnings: "Safe for short-term use including on face. Avoid prolonged application.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  clotrimazole: {
    uses: "Fungal skin infections (ringworm, athlete's foot), vaginal thrush.",
    howItWorks: "Azole antifungal that disrupts ergosterol in fungal cell membranes.",
    sideEffects: "Mild burning, itching, redness at application site.",
    warnings: "Complete full course. Avoid eyes. Vaginal form: don't use with latex condoms.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  terbinafine: {
    uses: "Fungal nail infections, ringworm, athlete's foot.",
    howItWorks: "Inhibits squalene epoxidase, depleting ergosterol in fungal cell membranes.",
    sideEffects: "Topical: mild irritation. Oral: nausea, rash, rare liver toxicity.",
    warnings: "Oral form: check LFTs before and during treatment. Avoid in liver disease.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  mupirocin: {
    uses: "Impetigo, bacterial skin infections (MRSA decolonisation).",
    howItWorks: "Topical antibiotic inhibiting bacterial isoleucyl-tRNA synthetase.",
    sideEffects: "Mild burning, stinging, itching at application site.",
    warnings: "For topical use only. Do not use for more than 10 days to prevent resistance.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  tretinoin: {
    uses: "Acne, photoageing, hyperpigmentation.",
    howItWorks: "Retinoid that increases skin cell turnover and regulates keratinisation.",
    sideEffects: "Skin redness, peeling, sensitivity to sunlight.",
    warnings: "Use sunscreen daily. Avoid in pregnancy. Start with low concentration.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  isotretinoin: {
    uses: "Severe or treatment-resistant acne.",
    howItWorks: "Oral retinoid that shrinks sebaceous glands and normalises skin-cell shedding.",
    sideEffects: "Dry lips/skin, elevated lipids, joint pain, teratogenicity.",
    warnings: "Absolutely contraindicated in pregnancy. Monthly pregnancy tests required.",
    prescriptionRequired: true,
    soldOnline: false,
  },
  "benzoyl peroxide": {
    uses: "Mild to moderate acne.",
    howItWorks: "Releases oxygen that kills Cutibacterium acnes bacteria and reduces inflammation.",
    sideEffects: "Skin dryness, redness, peeling, may bleach fabric.",
    warnings: "Avoid eye area and lips. Start with low concentration and increase gradually.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  calamine: {
    uses: "Skin itching, mild sunburn, insect bites, chickenpox blisters.",
    howItWorks: "Zinc-based lotion that soothes skin and reduces itch.",
    sideEffects: "Mild drying of skin.",
    warnings: "External use only. Do not apply to open wounds.",
    prescriptionRequired: false,
    soldOnline: true,
  },

  // ── Ophthalmology ─────────────────────────────────────────────────────────
  timolol: {
    uses: "Glaucoma (reduces elevated intraocular pressure).",
    howItWorks: "Beta-blocker that reduces aqueous humour production in the eye.",
    sideEffects: "Eye irritation, reduced heart rate, shortness of breath (systemic absorption).",
    warnings: "Avoid in asthma or heart block. Press inner corner of eye after instilling to reduce absorption.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  latanoprost: {
    uses: "Open-angle glaucoma, ocular hypertension.",
    howItWorks: "Prostaglandin analogue that increases aqueous humour outflow.",
    sideEffects: "Eye redness, gradual iris and eyelash changes (darkening/lengthening).",
    warnings: "Use at bedtime. Inform patients about permanent iris colour change.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  "moxifloxacin eye drops": {
    uses: "Bacterial conjunctivitis.",
    howItWorks: "Fluoroquinolone antibiotic that inhibits bacterial DNA gyrase in the eye.",
    sideEffects: "Eye irritation, mild burning, transient blurred vision.",
    warnings: "Do not wear contact lenses during treatment.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  "tobramycin eye drops": {
    uses: "Bacterial eye infections.",
    howItWorks: "Aminoglycoside antibiotic active against Gram-negative and staphylococcal eye pathogens.",
    sideEffects: "Eye irritation, stinging, lid itching.",
    warnings: "Do not wear contacts during use. Complete the full course.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  "sodium cromoglicate": {
    uses: "Allergic conjunctivitis, vernal keratoconjunctivitis.",
    howItWorks: "Mast cell stabiliser that prevents histamine release from mast cells in the eye.",
    sideEffects: "Mild transient stinging on instillation.",
    warnings: "Works best when started before allergy season.",
    prescriptionRequired: false,
    soldOnline: true,
  },

  // ── Gynaecology & Hormones ────────────────────────────────────────────────
  "oral contraceptive": {
    uses: "Contraception, menstrual regulation, acne, polycystic ovary syndrome.",
    howItWorks: "Oestrogen + progestogen combination prevents ovulation, thickens cervical mucus.",
    sideEffects: "Nausea, breast tenderness, spotting, mood changes, rare thrombosis.",
    warnings: "Increased VTE risk — avoid in smokers over 35, personal history of clots.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  "levonorgestrel": {
    uses: "Emergency contraception (within 72 hours), IUCD, hormonal contraception.",
    howItWorks: "Progestogen that delays or prevents ovulation and alters cervical mucus.",
    sideEffects: "Nausea, irregular bleeding, headache.",
    warnings: "Not for regular use as contraception. Not 100% effective.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  progesterone: {
    uses: "Luteal support in IVF, infertility, threatened miscarriage, HRT.",
    howItWorks: "Natural female hormone that prepares the uterus for implantation.",
    sideEffects: "Dizziness, drowsiness, breast tenderness.",
    warnings: "Vaginal/oral preparations differ in bioavailability. Follow prescribed route.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  mifepristone: {
    uses: "Medical termination of pregnancy (with misoprostol).",
    howItWorks: "Progesterone receptor antagonist that sensitises uterus to prostaglandins.",
    sideEffects: "Cramps, bleeding, nausea.",
    warnings: "Must be used under medical supervision. Follow up after 48 hours.",
    prescriptionRequired: true,
    soldOnline: false,
  },
  clomiphene: {
    uses: "Infertility due to anovulation, polycystic ovary syndrome.",
    howItWorks: "Selective oestrogen receptor modulator that stimulates ovulation.",
    sideEffects: "Hot flushes, visual disturbances, multiple pregnancies.",
    warnings: "Monitor with ultrasound. Do not use beyond 6 cycles.",
    prescriptionRequired: true,
    soldOnline: true,
  },

  // ── Urology ───────────────────────────────────────────────────────────────
  tamsulosin: {
    uses: "Benign prostatic hyperplasia (BPH) — relieves urinary symptoms.",
    howItWorks: "Alpha-1A receptor blocker relaxing smooth muscle in the prostate and bladder neck.",
    sideEffects: "Postural hypotension, retrograde ejaculation, dizziness.",
    warnings: "Rise slowly from sitting. Tell surgeon if taking before cataract surgery.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  finasteride: {
    uses: "BPH, male pattern baldness.",
    howItWorks: "5-alpha reductase inhibitor reducing DHT, shrinking the prostate.",
    sideEffects: "Reduced libido, erectile dysfunction, decreased ejaculate volume.",
    warnings: "Women should not handle crushed tablets (teratogenic). PSA level reduced by ~50%.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  sildenafil: {
    uses: "Erectile dysfunction, pulmonary arterial hypertension.",
    howItWorks: "PDE-5 inhibitor that increases cGMP, relaxing smooth muscle in corpus cavernosum.",
    sideEffects: "Headache, flushing, nasal congestion, visual tinges.",
    warnings: "Absolute contraindication with nitrates. Caution in cardiac disease.",
    prescriptionRequired: true,
    soldOnline: true,
  },

  // ── Oncology (common agents) ──────────────────────────────────────────────
  tamoxifen: {
    uses: "Oestrogen receptor-positive breast cancer treatment and prevention.",
    howItWorks: "Selective oestrogen receptor modulator blocking oestrogen's growth effects on breast tissue.",
    sideEffects: "Hot flushes, vaginal discharge, increased risk of uterine cancer and thrombosis.",
    warnings: "Annual gynaecological review recommended. Seek help for leg pain/swelling.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  anastrozole: {
    uses: "Postmenopausal oestrogen receptor-positive breast cancer.",
    howItWorks: "Aromatase inhibitor that blocks peripheral oestrogen synthesis.",
    sideEffects: "Hot flushes, joint pain, bone density loss.",
    warnings: "Bone density monitoring recommended. Calcium and D3 supplementation advised.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  imatinib: {
    uses: "Chronic myeloid leukaemia (CML), GIST.",
    howItWorks: "Tyrosine kinase inhibitor targeting BCR-ABL, c-Kit, and PDGFR fusion proteins.",
    sideEffects: "Oedema, nausea, muscle cramps, fatigue, low blood counts.",
    warnings: "Regular CBC and liver function tests. Take with food and water.",
    prescriptionRequired: true,
    soldOnline: false,
  },

  // ── Musculoskeletal & Others ──────────────────────────────────────────────
  colchicine: {
    uses: "Acute gout attack, prevention of gout, familial Mediterranean fever.",
    howItWorks: "Inhibits microtubule polymerisation, reducing neutrophil migration to inflamed joints.",
    sideEffects: "Diarrhoea, nausea, abdominal pain. Overdose: bone marrow suppression.",
    warnings: "Reduce dose in kidney or liver disease. Multiple drug interactions.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  allopurinol: {
    uses: "Prevention of gout, kidney stones from uric acid.",
    howItWorks: "Xanthine oxidase inhibitor reducing uric acid production.",
    sideEffects: "Rash, GI upset. Rare: severe hypersensitivity (Stevens-Johnson syndrome).",
    warnings: "Start after acute attack resolves. Check HLA-B*5801 in Southeast Asians before starting.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  "methyl prednisolone": {
    uses: "Allergic reactions, asthma, inflammatory conditions, autoimmune diseases.",
    howItWorks: "Potent corticosteroid that suppresses immune and inflammatory responses.",
    sideEffects: "Weight gain, elevated blood sugar, mood changes, increased infection risk.",
    warnings: "Do not stop abruptly after long use. Taper gradually.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  prednisolone: {
    uses: "Allergic conditions, asthma, rheumatoid arthritis, inflammatory bowel disease.",
    howItWorks: "Synthetic corticosteroid with potent anti-inflammatory and immunosuppressant effects.",
    sideEffects: "Weight gain, blood sugar rise, osteoporosis, cataracts on long-term use.",
    warnings: "Taper slowly from prolonged use. Bone protection (calcium+D3) for long-term therapy.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  dexamethasone: {
    uses: "Cerebral oedema, severe allergies, croup, COVID-19 (hospitalised), cancer-related inflammation.",
    howItWorks: "High-potency corticosteroid with strong anti-inflammatory action and low mineralocorticoid activity.",
    sideEffects: "Hyperglycaemia, insomnia, immunosuppression.",
    warnings: "Even single doses can raise blood sugar significantly in diabetics.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  hydroxyzine: {
    uses: "Anxiety (short-term), urticaria, pruritus.",
    howItWorks: "First-generation antihistamine with anxiolytic properties via H1 and CNS serotonin blockade.",
    sideEffects: "Sedation, dry mouth, dizziness.",
    warnings: "Impairs driving. Avoid alcohol.",
    prescriptionRequired: true,
    soldOnline: true,
  },
  "oral rehydration": {
    uses: "Rehydration after diarrhoea, vomiting, or excessive sweating.",
    howItWorks: "Glucose-sodium cotransport maximises intestinal water absorption.",
    sideEffects: "Generally very safe.",
    warnings: "Use clean water. Do not add extra salt or sugar.",
    prescriptionRequired: false,
    soldOnline: true,
  },
  "multivitamin": {
    uses: "Prevention and treatment of vitamin and mineral deficiencies.",
    howItWorks: "Provides essential micronutrients for metabolic processes and normal body function.",
    sideEffects: "Nausea if taken on empty stomach.",
    warnings: "Do not exceed stated dose. Fat-soluble vitamins (A, D, E, K) can accumulate.",
    prescriptionRequired: false,
    soldOnline: true,
  },
};

const KEYS = Object.keys(DRUG_DETAILS);

export function lookupDrugDetail(
  brandName?: string | null,
  ingredients?: string | null,
  saltComposition?: string | null,
): DrugDetail | null {
  const candidates: string[] = [];
  if (brandName) candidates.push(brandName.toLowerCase());
  if (saltComposition) candidates.push(saltComposition.toLowerCase());
  if (ingredients) {
    try {
      const parsed = JSON.parse(ingredients);
      if (Array.isArray(parsed)) {
        for (const i of parsed) {
          if (i?.name) candidates.push(String(i.name).toLowerCase());
        }
      }
    } catch {
      candidates.push(ingredients.toLowerCase());
    }
  }

  for (const c of candidates) {
    for (const k of KEYS) {
      if (c.includes(k)) return DRUG_DETAILS[k];
    }
  }
  return null;
}
